#pragma once

// AUTO-GENERATED - DO NOT EDIT
// String IDs for FlipperHack runtime string table

#define STR_FLIPPERHACK          0      // "flipperhack"
#define STR_VERSION              1      // "0.01a"
#define STR_WELCOME              2      // "Welcome to FlipperHack!"
#define STR_NOT_IMPLEMENTED      3      // "Not implemented yet!"
#define STR_EMPTY                4      // "<EMPTY>"
#define STR_ALLOC_FAIL           5      // "Alloc fail: "
#define STR_OPEN_FAIL            6      // "Open fail: "
#define STR_SD_FAIL              7      // "SD Card Fail!"
#define STR_RECORD_STORAGE_FAIL  8      // "RECORD_STORAGE fail!"
#define STR_ROM_FAIL             9      // "ROM Fail!"
#define STR_MISSING_IMAGE        10     // "Missing/Bad image!"
#define STR_INVALID_OPCODE       11     // "Invalid OpieScript opcode: "
#define STR_GFX_DIR              12     // "/ext/apps_data/flipperhack/gfx/"
#define STR_TITLE_BIN            13     // "title.bin"
#define STR_GAMEOVER_BIN         14     // "gameover.bin"
#define STR_CANT_JUMP            15     // "You can't leap into space."
#define STR_ASCEND               16     // "Ascended Stairs. Level "
#define STR_DESCEND              17     // "Descended Stairs. Level "
#define STR_NO_STAIRS            18     // "No stairs here."
#define STR_PATH_BLOCKED         19     // "The path is blocked."
#define STR_WALL_RUB             20     // "You rub the wall."
#define STR_WALL_FACEHUG         21     // "You facehug the wall."
#define STR_HP_LOG               22     // "HP: "
#define STR_CURSOR_MODE          23     // "Cursor Mode"
#define STR_DIRECTION_SELECT     24     // "Direction Select"
#define STR_SELECTED             25     // "Selected: "
#define STR_UNKNOWN              26     // "Unknown"
#define STR_YOU                  27     // "You"
#define STR_STAIRS               28     // "Stairs"
#define STR_DOOR                 29     // "Door"
#define STR_INVENTORY            30     // "Inventory"
#define STR_EQUIPMENT            31     // "Equipment"
#define STR_MEMORY               32     // "Memory"
#define STR_ENEMIES              33     // "Enemies"
#define STR_CURSOR               34     // "Cursor"
#define STR_NEW_GAME             35     // "New Game"
#define STR_QUIT                 36     // "Quit"
#define STR_MAIN_MENU            37     // "Main Menu"
#define STR_GAME_MENU            38     // "Game Menu"
#define STR_DEBUG                39     // "Debug"
#define STR_BACK                 40     // "Back"
#define STR_EXIT                 41     // "Exit"
#define STR_GOBLIN               42     // "Goblin"
#define STR_HEALTH_POTION        43     // "Health Potion"
#define STR_WALL                 44     // "Wall"
#define STR_FLOOR                45     // "Floor"
#define STR_DOOR_OPENED          46     // "Door (Opened)"
#define STR_DOOR_CLOSED          47     // "Door (Closed)"
#define STR_STAIRS_UP            48     // "Stairs (Up)"
#define STR_STAIRS_DOWN          49     // "Stairs (Down)"
#define STR_TELEPORT             50     // "Teleport"
