#pragma once

// AUTO-GENERATED - DO NOT EDIT
// String IDs for FlipperHack runtime string table

#define STR_FLIPPERHACK          0      // "flipperhack"
#define STR_VERSION              1      // "0.01a"
#define STR_WELCOME              2      // "Welcome to FlipperHack!"
#define STR_NOT_IMPLEMENTED      3      // "Not implemented yet!"
#define STR_EMPTY                4      // "<EMPTY>"
#define STR_ALLOC_FAIL           5      // "Alloc fail: "
#define STR_OPEN_FAIL            6      // "Open fail: "
#define STR_SD_FAIL              7      // "SD Card Fail!"
#define STR_RECORD_STORAGE_FAIL  8      // "RECORD_STORAGE fail!"
#define STR_ROM_FAIL             9      // "ROM Fail!"
#define STR_MISSING_IMAGE        10     // "Missing/Bad image!"
#define STR_INVALID_OPCODE       11     // "Invalid OpieScript opcode: "
#define STR_OPIESCRIPT           12     // "OpieScript"
#define STR_GFX_DIR              13     // "/ext/apps_data/flipperhack/gfx/"
#define STR_TITLE_BIN            14     // "title.bin"
#define STR_GAMEOVER_BIN         15     // "gameover.bin"
#define STR_CANT_JUMP            16     // "You can't leap into space."
#define STR_ASCEND               17     // "Ascended Stairs. Level "
#define STR_DESCEND              18     // "Descended Stairs. Level "
#define STR_NO_STAIRS            19     // "No stairs here."
#define STR_PATH_BLOCKED         20     // "The path is blocked."
#define STR_WALL_RUB             21     // "You rub the wall."
#define STR_WALL_FACEHUG         22     // "You facehug the wall."
#define STR_HP_LOG               23     // "HP: "
#define STR_CURSOR_MODE          24     // "Cursor Mode"
#define STR_DIRECTION_SELECT     25     // "Direction Select"
#define STR_SELECTED             26     // "Selected: "
#define STR_UNKNOWN              27     // "Unknown"
#define STR_YOU                  28     // "You"
#define STR_STAIRS               29     // "Stairs"
#define STR_DOOR                 30     // "Door"
#define STR_INVENTORY            31     // "Inventory"
#define STR_EQUIPMENT            32     // "Equipment"
#define STR_MEMORY               33     // "Memory"
#define STR_ENEMIES              34     // "Enemies"
#define STR_CURSOR               35     // "Cursor"
#define STR_NEW_GAME             36     // "New Game"
#define STR_QUIT                 37     // "Quit"
#define STR_MAIN_MENU            38     // "Main Menu"
#define STR_GAME_MENU            39     // "Game Menu"
#define STR_DEBUG                40     // "Debug"
#define STR_BACK                 41     // "Back"
#define STR_EXIT                 42     // "Exit"
#define STR_GOBLIN               43     // "Goblin"
#define STR_HEALTH_POTION        44     // "Health Potion"
#define STR_WALL                 45     // "Wall"
#define STR_FLOOR                46     // "Floor"
#define STR_DOOR_OPENED          47     // "Door (Opened)"
#define STR_DOOR_CLOSED          48     // "Door (Closed)"
#define STR_STAIRS_UP            49     // "Stairs (Up)"
#define STR_STAIRS_DOWN          50     // "Stairs (Down)"
#define STR_TELEPORT             51     // "Teleport"
