#pragma once

// AUTO-GENERATED — DO NOT EDIT
// String IDs for FlipperHack runtime string table

#define STR_FLIPPERHACK          0      // "flipperhack"
#define STR_VERSION              1      // "0.01a"
#define STR_WELCOME              2      // "Welcome to FlipperHack!"
#define STR_NOT_IMPLEMENTED      3      // "Not implemented yet!"
#define STR_EMPTY                4      // "<EMPTY>"
#define STR_ALLOC_FAIL           5      // "Alloc fail: "
#define STR_OPEN_FAIL            6      // "Open fail: "
#define STR_SD_FAIL              7      // "SD Card Fail!"
#define STR_RECORD_STORAGE_FAIL  8      // "RECORD_STORAGE fail!"
#define STR_ROM_FAIL             9      // "ROM Fail!"
#define STR_MISSING_IMAGE        10     // "Missing/Bad image!"
#define STR_GFX_DIR              11     // "/ext/apps_data/flipperhack/gfx/"
#define STR_TITLE_BIN            12     // "title.bin"
#define STR_GAMEOVER_BIN         13     // "gameover.bin"
#define STR_CANT_JUMP            14     // "You can't leap into space."
#define STR_ASCEND               15     // "Ascended Stairs. Level "
#define STR_DESCEND              16     // "Descended Stairs. Level "
#define STR_NO_STAIRS            17     // "No stairs here."
#define STR_PATH_BLOCKED         18     // "The path is blocked."
#define STR_WALL_RUB             19     // "You rub the wall."
#define STR_WALL_FACEHUG         20     // "You facehug the wall."
#define STR_HP_LOG               21     // "HP: "
#define STR_CURSOR_MODE          22     // "Cursor Mode"
#define STR_DIRECTION_SELECT     23     // "Direction Select"
#define STR_SELECTED             24     // "Selected: "
#define STR_UNKNOWN              25     // "Unknown"
#define STR_YOU                  26     // "You"
#define STR_STAIRS               27     // "Stairs"
#define STR_DOOR                 28     // "Door"
#define STR_INVENTORY            29     // "Inventory"
#define STR_EQUIPMENT            30     // "Equipment"
#define STR_MEMORY               31     // "Memory"
#define STR_ENEMIES              32     // "Enemies"
#define STR_CURSOR               33     // "Cursor"
#define STR_NEW_GAME             34     // "New Game"
#define STR_QUIT                 35     // "Quit"
#define STR_MAIN_MENU            36     // "Main Menu"
#define STR_GAME_MENU            37     // "Game Menu"
#define STR_DEBUG                38     // "Debug"
#define STR_BACK                 39     // "Back"
#define STR_GOBLIN               40     // "Goblin"
#define STR_HEALTH_POTION        41     // "Health Potion"
#define STR_WALL                 42     // "Wall"
#define STR_FLOOR                43     // "Floor"
#define STR_DOOR_OPENED          44     // "Door (Opened)"
#define STR_DOOR_CLOSED          45     // "Door (Closed)"
#define STR_STAIRS_UP            46     // "Stairs (Up)"
#define STR_STAIRS_DOWN          47     // "Stairs (Down)"
#define STR_TELEPORT             48     // "Teleport"
